"""
Aggregation point for all application prompt templates.
Splitting prompts into sub-modules improves readability and organization.
"""

from .main import (
    DEFAULT_COPY_MERGED_PROMPT,
    DEFAULT_INTRO_PROMPT,
    DEFAULT_OUTRO_PROMPT,
    COMMENT_CLEANUP_PROMPT,
    DEAD_WEIGHT_PROMPT,
    DRY_UP_PROMPT,
    MAGIC_NUMBER_PROMPT,
    BRUTAL_REVIEW_PROMPT,
    ELI5_PROMPT,
    ORDER_REQUEST_PROMPT_TEMPLATE,
    SPLIT_FILE_PROMPT_TEMPLATE
)

from .surgical import (
    INSTR_FAST_APPLY,
    EXAMPLE_FAST_APPLY,
    SURGICAL_AMBIGUOUS_PROMPT_TEMPLATE,
    SURGICAL_MISMATCH_PROMPT_TEMPLATE,
    SURGICAL_UNIQUENESS_INSTRUCTION
)

from .formatting import (
    FORMATTING_INSTRUCTION_TEMPLATE,
    AUTOMATION_WARNING_TEMPLATE,
    FORMAT_CORRECTION_PROMPT_TEMPLATE,
    ORDER_CORRECTION_PROMPT_TEMPLATE
)

from .starter import (
    STARTER_CONCEPT_DEFAULT_GOAL,
    STARTER_CONCEPT_PROMPT_INTRO,
    STARTER_CONCEPT_PROMPT_CORE_INSTR,
    STARTER_STACK_PROMPT_INTRO,
    STARTER_STACK_PROMPT_INSTR,
    STARTER_DESIGN_PROMPT_INTRO,
    STARTER_DESIGN_PROMPT_INSTR,
    STARTER_PIVOT_PROMPT_TEMPLATE,
    STARTER_TODO_PROMPT_INTRO,
    STARTER_TODO_PROMPT_INSTR,
    STARTER_GENERATE_MASTER_INTRO,
    STARTER_GENERATE_MASTER_INSTR,
    STARTER_REWRITE_PROMPT_TEMPLATE,
    STARTER_SYNC_PROMPT_TEMPLATE,
    STARTER_QUESTION_PROMPT_TEMPLATE,
    STARTER_DEFAULT_SCAFFOLD_INTRO_TEMPLATE,
    STARTER_SECTION_INSTRUCTIONS_TEMPLATE,
    STARTER_REFERENCE_PROJECT_HEADER,
    STARTER_NAME_SUGGESTIONS_PROMPT_TEMPLATE
)

from .visualizer import (
    VISUALIZER_GENERATION_PROMPT,
    VISUALIZER_AMEND_PROMPT,
    VISUALIZER_UPDATE_PROMPT,
    VISUALIZER_ERROR_PROMPT_TEMPLATE
)