export const starterInfo = {
  // Project Starter
  "starter_nav_prev": "Previous Step: Go back to review or change settings in earlier steps.",
  "starter_nav_next": "Next Step: Proceed to the next phase. Validates current input before moving.",
  "starter_nav_reset": "Reset Step: Clear the current form or editor to start this specific step over.",
  "starter_header_save": "Save Config: Export your current project configuration (concept, stack, plan) to a JSON file.",
  "starter_header_load": "Load Config: Restore a previously saved project configuration.",
  "starter_header_clear": "Clear All: Completely reset the project starter to the beginning.",
  "starter_header_exit": "Save and Exit: Closes the Project Starter. If you have entered any data, it is automatically saved to a persistent session file so you can resume your progress later.",
  "starter_details_name": "Project Name: The name of your application. This will be used for the folder name and the README title.",
  "starter_details_base": "Base Project: Optionally select an existing folder to use as a reference. Useful for 'v2' rewrites or analyzing existing code.",
  "starter_concept_goal": "User Goal: Briefly describe what you want to build. This is the seed for the AI to generate the full concept.",
  "starter_concept_gen": "Generate Concept: Copies a structured prompt to your clipboard. You must paste this into your LLM to generate the features list and user flow, then copy the result back here.",
  "starter_concept_review": "Concept Review: Review and manually edit the generated project concept document.",
  "starter_gen_response": "Paste Response: Paste the LLM's output here. CodeMerger will look for specific tags or file markers to process.",
  "starter_gen_process": "Process Response: Analyze the pasted LLM output to populate the internal drafts.",
  "starter_stack_exp": "Experience: List your known languages and frameworks. The AI will recommend a stack that matches your skills.",
  "starter_stack_gen": "Generate Stack: Copies a prompt to your clipboard asking for technology recommendations.",
  "starter_stack_edit": "Stack List: Review and manually adjust the suggested technologies.",
  "starter_stack_item": "Stack Subject: Click the header bar to reveal the architectural rationale behind this choice. Manual entries do not have rationales.",
  "starter_stack_edit_name": "Edit Subject: Modify the name of this technology. Changes are saved automatically when you click away.",
  "starter_stack_delete": "Remove Subject: Take this technology out of your stack. A confirmation will appear showing the technical impact of this removal.",
  "starter_stack_rationale": "Technical Rationale: A detailed explanation from the AI describing why this specific technology is the optimal fit for your project requirements.",
  "starter_stack_add": "Add Subject: Manually insert a new technology or tool. Manual items are treated as simple labels without AI-generated reasoning.",
  "starter_stack_delete_warning": "Architectural Warning: A specific consequence provided by the AI, explaining what technical hurdles would be introduced if this item is removed.",
  "starter_todo_gen": "Generate Plan: Copies a prompt to your clipboard to create a step-by-step implementation plan (todo.md).",
  "starter_todo_review": "Plan Review: Review and manually edit the implementation tasks and phases.",
  "starter_gen_parent": "Parent Folder: The directory where your new project folder will be created.",
  "starter_gen_prompt": "Master Prompt: Copies the final boilerplate instruction to your clipboard. Paste this into your LLM to generate the initial codebase.",
  "starter_gen_create": "Create Project: Parse the LLM's code blocks and write the final files to disk to initialize your project.",
  "starter_seg_nav": "Segment Navigation: Jump between different sections of the generated document.",
  "starter_seg_indicator": "Lock Status: Toggle the sign-off status for this segment. Locked segments are used as immutable references in 'Rewrite' operations.",
  "starter_seg_questions": "Questions Toggle: Show or hide the guiding questions panel to help refine the quality of this segment.",
  "starter_questions_panel": "Guiding Questions: Review these specific criteria to ensure the current segment is comprehensive and accurate. Use the navigation arrows to cycle through different focus points.",
  "starter_questions_copy": "Copy Question Prompt: Compiles the current segment's text, any surrounding context, and the selected guiding question into a structured prompt. Paste this into your LLM to get specific feedback or verification.",
  "starter_questions_custom": "Custom Question: Type your own specific question or instruction for the AI regarding this content. This allows you to go beyond the prewritten guiding questions.",
  "starter_seg_rewrite": "Rewrite Segments: Provide a specific instruction to rewrite all unsigned segments based on new feedback.",
  "starter_seg_signoff": "Sign Off: Lock the current segment and move to the next incomplete section.",
  "starter_seg_unlock": "Unlock: Release the lock on this segment to allow further manual edits or inclusion in a Rewrite.",
  "starter_seg_merge": "Merge: Finalize and combine all individual segments into a single Markdown document.",
  "starter_seg_sync": "Sync: Propagate your manual changes from this segment to other unsigned segments to maintain consistency.",
  "starter_view_toggle": "View Toggle: Switch between a raw text editor for manual changes and a stylized Markdown preview.",

  "starter_success_path": "Project Location: The full path to your newly created project directory.",
  "starter_success_open": "Open Folder: Reveal the new project directory in your system's file explorer.",
  "starter_success_activate": "Activate Project: Load the new project into CodeMerger immediately and close the starter.",
  "starter_success_exit": "Close: Exit the Project Starter.",

  // Rewrite Dialog
  "rewrite_instruction": "Modification Instruction: Tell the AI what you want to change in the project drafts (e.g., 'Use a more formal tone' or 'Add a SQLite database').",
  "rewrite_copy_prompt": "Generate Prompt: Compiles your instructions with the current drafts and locked segments into a single prompt for the LLM.",
  "rewrite_response": "Paste Response: Paste the LLM's updated content here to refresh the drafts.",
  "rewrite_apply": "Apply Changes: Process the response and update the starter drafts. Any summary notes from the AI will be displayed.",
  "rewrite_cancel": "Cancel: Discard the current rewrite session and return to the project review without applying any changes."
};