# --- Application Constants ---
from .core.paths import CONFIG_FILE_PATH, DEFAULT_FILETYPES_CONFIG_PATH, VERSION_FILE_PATH

# Configuration file names
CONFIG_FILE = CONFIG_FILE_PATH
DEFAULT_FILETYPES_CONFIG = DEFAULT_FILETYPES_CONFIG_PATH
VERSION_FILE = VERSION_FILE_PATH

# Default prompt for the "Copy Merged" action
DEFAULT_COPY_MERGED_PROMPT = "Here is the most recent code, please use this when making changes:\n\n"

# --- Limits and UI settings ---
RECENT_PROJECTS_MAX = 10
SUBTLE_HIGHLIGHT_COLOR = "#555555"
COMPACT_MODE_BG_COLOR = "#6f6f6f"

# --- UI Color Palette ---
DARK_BG = '#2E2E2E'
TOP_BAR_BG = '#252525'
TEXT_COLOR = '#FFFFFF'
TEXT_SUBTLE_COLOR = '#A0A0A0'
TEXT_INPUT_BG = '#3C3C3C'
BTN_BLUE = '#0078D4'
BTN_BLUE_TEXT = '#FFFFFF'
BTN_GRAY_BG = '#CCCCCC'
BTN_GRAY_TEXT = '#333333'
WRAPPER_BORDER = '#555555'
STATUS_BG = '#3A3A3A'
STATUS_FG = '#D3D3D3'