# --- Application Constants ---
from .paths import CONFIG_FILE_PATH, DEFAULT_FILETYPES_CONFIG_PATH, VERSION_FILE_PATH

# Configuration file names
CONFIG_FILE = CONFIG_FILE_PATH
DEFAULT_FILETYPES_CONFIG = DEFAULT_FILETYPES_CONFIG_PATH
VERSION_FILE = VERSION_FILE_PATH

# --- Limits and UI settings ---
RECENT_DIRS_MAX = 5
SUBTLE_HIGHLIGHT_COLOR = "#f0f0f0"