name: Build on macOS

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m venv cm-venv
          source cm-venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build with PyInstaller
        run: |
          source cm-venv/bin/activate
          pyinstaller codemerger.spec

      - name: List build output
        if: always()
        run: |
          echo "--- Listing contents of dist directory ---"
          ls -R dist

      - name: Upload macOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeMerger-macOS
          path: dist/CodeMerger.app
          if-no-files-found: error