name: Create Release

# Runs when a new tag is pushed (format v*.*.*)
on:
  push:
    tags:
      - 'v*'

jobs:
  validate-tag:
    name: Validate Release Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify tag is on the master branch
        run: |
          TAG="${{ github.ref_name }}"
          echo "Validating tag: $TAG"
          TAG_COMMIT_HASH=$(git rev-parse "$TAG")
          if ! git branch -r --contains "$TAG_COMMIT_HASH" | grep -q "origin/master"; then
            echo "::error::Tag $TAG points to a commit that is not on the 'master' branch."
            echo ""
            echo "To fix this, delete the incorrect tag and create a new one on a commit in 'master'."
            echo "Run the following commands in your local terminal:"
            echo ""
            echo "  git push --delete origin $TAG"
            echo "  git tag -d $TAG"
            echo ""
            exit 1
          fi
          echo "Tag validation successful: $TAG is on the master branch."

  build-windows:
    name: Build for Windows
    needs: validate-tag
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build with PyInstaller
        run: pyinstaller codemerger.spec
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeMerger-windows-exe
          path: dist/CodeMerger.exe

  build-mac-universal:
    name: Build Universal macOS App
    needs: validate-tag
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build dependencies via Homebrew
        run: brew install jpeg-xl libtiff
      - name: Install Python dependencies
        env:
          ARCHFLAGS: "-arch arm64 -arch x86_64"
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir --no-binary Pillow -r requirements.txt
          python -m pip install delocate
      - name: Build with PyInstaller
        run: pyinstaller codemerger.spec
      - name: Repair app bundle with delocate
        run: |
          SCRIPTS_DIR=$(python -c "import sysconfig; print(sysconfig.get_path('scripts'))")
          "$SCRIPTS_DIR/delocate-path" -v -d dist/CodeMerger.app
      - name: Zip the application bundle
        run: |
          cd dist
          zip -r ../CodeMerger-macOS.zip CodeMerger.app
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeMerger-macOS-zip
          path: CodeMerger-macOS.zip

  create-release:
    name: Create GitHub Release
    needs: [build-windows, build-mac-universal]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: |
            artifacts/CodeMerger-windows-exe/CodeMerger.exe
            artifacts/CodeMerger-macOS-zip/CodeMerger-macOS.zip