name: Create Release

# Run when a new tag is pushed (format v*.*.*)
on:
  push:
    tags:
      - 'v*'

jobs:
  # Build for Windows
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller codemerger.spec

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeMerger-windows-exe
          path: dist/CodeMerger.exe

  # Build for macOS
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller codemerger.spec

      - name: Compress .app into a .zip file
        run: zip -r dist/CodeMerger-macOS.zip dist/CodeMerger.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: CodeMerger-macOS-zip
          path: dist/CodeMerger-macOS.zip

  # Create the GitHub Release (runs after both build jobs have succeeded)
  create-release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false
          files: |
            artifacts/CodeMerger-windows-exe/CodeMerger.exe
            artifacts/CodeMerger-macOS-zip/CodeMerger-macOS.zip